### ISSUE TITLE
Transfer to HEP-FCC

### ISSUE THREAD

**Issue by vvolkl** [HEP-FCC/dual-readout#2]
Hi @SanghyunKo ,

I think now would be a good time to start putting integrating this detector more in FCC software. A first step would be to have this in the HEP-FCC github organization - I already added you as a member. Could you transfer the repository to https://github.com/HEP-FCC? See https://docs.github.com/en/github/administering-a-repository/transferring-a-repository
Cheers,
Valentin

**Comment by SanghyunKo** [comment]
Hi @vvolkl , the repository has just been transferred. I have a few notes - this application was originally intended to work as a standalone package, so it has many duplicated parts (some of them are that I already borrowed from FCCSW) such as DDG4, file I/O, event generator, etc. Hence probably you would only need to take a look into `Detector/...`, `Sim/...`, `Reco/...`. I intentionally mimicked the structure of FCCSW for these parts, so I believe they may not require many significant changes in the design. Still, the integration & review will take a quite of time and efforts - please ping me whenever you need me.
